# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trade.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trade.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrade.proto\x12\x05trade\"j\n\x0cOrderRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x15\n\rtrigger_price\x18\x03 \x01(\x01\x12\x11\n\tcondition\x18\x04 \x01(\t\x12\x10\n\x08quantity\x18\x05 \x01(\x05\"\x90\x01\n\nTradeEvent\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x15\n\rtrigger_price\x18\x03 \x01(\x01\x12\x16\n\x0e\x65xecuted_price\x18\x04 \x01(\x01\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\"!\n\rCancelRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"2\n\x0e\x43\x61ncelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x84\x01\n\x0eTradingService\x12\x36\n\nPlaceOrder\x12\x13.trade.OrderRequest\x1a\x11.trade.TradeEvent0\x01\x12:\n\x0b\x43\x61ncelOrder\x12\x14.trade.CancelRequest\x1a\x15.trade.CancelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trade_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=22
  _globals['_ORDERREQUEST']._serialized_end=128
  _globals['_TRADEEVENT']._serialized_start=131
  _globals['_TRADEEVENT']._serialized_end=275
  _globals['_CANCELREQUEST']._serialized_start=277
  _globals['_CANCELREQUEST']._serialized_end=310
  _globals['_CANCELRESPONSE']._serialized_start=312
  _globals['_CANCELRESPONSE']._serialized_end=362
  _globals['_TRADINGSERVICE']._serialized_start=365
  _globals['_TRADINGSERVICE']._serialized_end=497
# @@protoc_insertion_point(module_scope)
